from .node_video_sizes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .node_flat_shade import NODE_CLASS_MAPPINGS as _FLAT_MAP, NODE_DISPLAY_NAME_MAPPINGS as _FLAT_NAMES
from .node_mesh_bridge import NODE_CLASS_MAPPINGS as _BRIDGE_MAP, NODE_DISPLAY_NAME_MAPPINGS as _BRIDGE_NAMES
from .node_flat_shade_trimesh import NODE_CLASS_MAPPINGS as _TRIMESH_MAP, NODE_DISPLAY_NAME_MAPPINGS as _TRIMESH_NAMES
from .node_trimesh_to_file3d import NODE_CLASS_MAPPINGS as _F3D_MAP, NODE_DISPLAY_NAME_MAPPINGS as _F3D_NAMES
from .node_aspect_ratio_size_picker import NODE_CLASS_MAPPINGS as _AR_MAP, NODE_DISPLAY_NAME_MAPPINGS as _AR_NAMES
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **_FLAT_MAP, **_BRIDGE_MAP, **_TRIMESH_MAP, **_F3D_MAP, **_AR_MAP}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **_FLAT_NAMES, **_BRIDGE_NAMES, **_TRIMESH_NAMES, **_F3D_NAMES, **_AR_NAMES}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
